TREEROOT = ../..

PROJECT_SRC = main.c

PROJECT = demo

# for freertos minimal/full demo
include ./Makefile.demo

# need to include this makefile for common setting for all program
include $(TREEROOT)/Makefile.common
